ELECT COUNT(IDBIEN), CATEGORIE, TYPE FROM BIEN 
GROUP BY CATEGORIE, TYPE;

SELECT IDE, DESIGNATION FROM ESPACE
CONNECT BY PRIOR IDE = IDERATTACH
START WITH IDE = 945;

SELECT IDP FROM PROPRIO
MINUS
SELECT IDP FROM BIEN
WHERE VILLE = 'MARSEILLE';

SELECT CATEGORIE FROM BIEN
WHERE CATEGORIE = 'MAISONS DE VILLE'
GROUP BY VILLE
HAVING COUNT(*) >= 10;

SELECT BIEN.IDEBIEN, (BIEN.PRIX - B_MIN.PRIX) FROM BIEN, BIEN B_MIN
WHERE BIEN.IDEBIEN = B_MIN.IDEBIEN AND B_MIN.PRIX = (SELECT MIN(BIEN.PRIX) FROM BIEN);

SELECT BIEN.IDEBIEN, (BIEN.PRIX - B_MIN.PRIX) FROM BIEN, BIEN B_MIN
WHERE BIEN.IDEBIEN = B_MIN.IDEBIEN AND B_MIN.PRIX = (SELECT MIN(BIEN.PRIX) FROM BIEN, B_MIN
                                                     WHERE BIEN.CATEGORIE = B_MIN.CATEGORIE);
