--Q1

SELECT COUNT(IDEBIEN), CATEGORIE, TYPE FROM BIEN 
GROUP BY CATEGORIE, TYPE;


--Q2

SELECT IDE, DESIGNATION FROM ESPACE
CONNECT BY PRIOR IDE = IDERATTACH
START WITH IDE = 945;

--Q3

SELECT IDP FROM PROPRIO
MINUS
SELECT IDP FROM BIEN
WHERE VILLE = 'MARSEILLE';

--Q4

SELECT VILLE FROM BIEN
WHERE CATEGORIE = 'MAISONS DE VILLE'
GROUP BY VILLE
HAVING COUNT(*) >= 10;

--Q5

SELECT BIEN.IDEBIEN, (BIEN.PRIX - B_MIN.PRIX) FROM BIEN, BIEN B_MIN
WHERE B_MIN.PRIX =(SELECT MIN(BIEN.PRIX) FROM BIEN);

--Q6

SELECT IdEBien, Categorie, Type, Ville, PRIX, (PRIX - (SELECT MIN(PRIX) 
FROM BIEN B
WHERE B.Categorie = BIEN.Categorie)) AS Ecart
FROM BIEN;

--Q7

CREATE VIEW Q7(IDP, NBR_BIEN) AS
SELECT IdP, COUNT(IdEBien)
FROM BIEN
WHERE BIEN.Type = 'Studio'
GROUP BY IDP
HAVING COUNT(IDEBIEN) >= 2;

SELECT Q7.IDP, COUNT(BIEN.IDEBIEN) FROM Q7, BIEN
WHERE Q7.IDP = BIEN.IDP
GROUP BY Q7.IDP;

--Q8

SELECT BIEN.IDP, NOM, PRENOM FROM BIEN
JOIN PROPRIO
ON BIEN.IDP = PROPRIO.IDP
GROUP BY BIEN.IDP, PROPRIO.NOM, PROPRIO.PRENOM
HAVING COUNT(DISTINCT BIEN.CATEGORIE) = (SELECT COUNT(DISTINCT CATEGORIE) FROM BIEN);

--Q9

SELECT IDEBIEN FROM BIEN, ESPACE
WHERE BIEN.IDEBIEN = ESPACE.IDERATTACH AND IDE IN (SELECT IDE FROM ESPACE
                                                   WHERE SUPERFICIE = (SELECT MAX(SUPERFICIE) FROM ESPACE));

--Q10
              
SELECT DISTINCT IDP FROM BIEN
WHERE NOT EXISTS(SELECT DISTINCT CATEGORIE FROM BIEN
                 WHERE IDP = 105 AND NOT EXISTS(
                        SELECT DISTINCT B2.CATEGORIE FROM BIEN B2
                        WHERE B2.IDP = BIEN.IDP AND NOT EXISTS(
                                SELECT DISTINCT B3.CATEGORIE FROM BIEN B3
                                WHERE B3.IDP = BIEN.IDP AND NOT EXISTS(
                                        SELECT DISTINCT CATEGORIE FROM BIEN
                                        WHERE IDP = 105))));
