
--Q1

SELECT COUNT(IDEBIEN), CATEGORIE, TYPE FROM BIEN 
GROUP BY CATEGORIE, TYPE;


--Q2

SELECT IDE, DESIGNATION FROM ESPACE
CONNECT BY PRIOR IDE = IDERATTACH
START WITH IDE = 945;

--Q3 

SELECT IDP FROM PROPRIO
MINUS
SELECT IDP FROM BIEN
WHERE VILLE = 'MARSEILLE';

--Q4 

SELECT VILLE FROM BIEN
WHERE CATEGORIE = 'MAISONS DE VILLE'
GROUP BY VILLE
HAVING COUNT(*) >= 10;

--Q5

SELECT BIEN.IDEBIEN, (BIEN.PRIX - B_MIN.PRIX) FROM BIEN, BIEN B_MIN
WHERE B_MIN.PRIX =(SELECT MIN(BIEN.PRIX) FROM BIEN);

--Q6 

SELECT IdEBien, (PRIX - (SELECT MIN(PRIX) 
FROM BIEN B
WHERE B.Categorie = BIEN.Categorie)) AS Ecart
FROM BIEN;

--Q7

CREATE OR REPLACE VIEW Q7(IDP, NBR_BIEN) AS
SELECT IdP, COUNT(IdEBien)
FROM BIEN
WHERE BIEN.Type = 'STUDIO'
GROUP BY IDP
HAVING COUNT(IDEBIEN) >= 2;

SELECT Q7.IDP, COUNT(BIEN.IDEBIEN) FROM Q7, BIEN
WHERE Q7.IDP = BIEN.IDP
GROUP BY Q7.IDP;

--Q8

SELECT BIEN.IDP, NOM, PRENOM FROM BIEN
JOIN PROPRIO
ON BIEN.IDP = PROPRIO.IDP
GROUP BY BIEN.IDP, PROPRIO.NOM, PROPRIO.PRENOM
HAVING COUNT(DISTINCT BIEN.CATEGORIE) = (SELECT COUNT(DISTINCT CATEGORIE) FROM BIEN);

--Q9 

SELECT IDEBIEN FROM BIEN, ESPACE
WHERE BIEN.IDEBIEN = ESPACE.IDE AND IDE IN (SELECT IDERATTACH FROM ESPACE
                                            WHERE DESIGNATION = 'TERRASSE' AND SUPERFICIE = (SELECT MAX(SUPERFICIE) FROM ESPACE
                                                                                             WHERE DESIGNATION = 'TERRASSE'));
--Q10 

SELECT DISTINCT BIEN.IDP
FROM BIEN
WHERE BIEN.CATEGORIE IN (
    SELECT DISTINCT B1.CATEGORIE
    FROM BIEN B1
    WHERE B1.IDP = 105
) AND BIEN.IDP != 105;

--Q11 

CREATE OR REPLACE VIEW Q12(CATEGORIE, MIN_CAT) AS
SELECT BIEN.CATEGORIE, (SELECT MIN(BIEN.PRIX) FROM BIEN, BIEN B_MIN WHERE BIEN.CATEGORIE = B_MIN.CATEGORIE) 
FROM BIEN, BIEN B_MIN
GROUP BY BIEN.CATEGORIE;

SELECT BIEN.IDEBIEN, (BIEN.PRIX - Q12.MIN_CAT) AS ECART
FROM BIEN, Q12
WHERE BIEN.CATEGORIE = Q12.CATEGORIE;
